apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    {{- include "yarp-ingress.labels" . | nindent 4 }}
  name: {{ .Values.ingressClass.name }}
  {{- if or .Values.ingressClass.default .Values.ingressClass.annotations }}
  annotations:
    {{- if .Values.ingressClass.default }}
    ingressclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    {{- if .Values.ingressClass.annotations }}
    {{- toYaml .Values.ingressClass.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  controller: {{ .Values.ingressClass.controllerValue }}
  {{- with .Values.ingressClass.parameters }}
  parameters: {{ toYaml . | nindent 4 }}
  {{- end }}
