name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: [
          # { version: 9.0.x, framework: net9.0 },
          { version: 10.0.x, framework: net10.0 }
        ]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet.version }}

      - run: dotnet build --configuration Release --framework ${{ matrix.dotnet.framework }}
      